name: Build

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build

      - name: Rename and prepare artifact
        run: |
          cd build/libs
          export JAR=$(find . -regex '.*liquidbounce-b[0-9|.]*\.jar')
          export LB_VERSION=$(echo $JAR | sed -r 's/.\/liquidbounce-([a-zA-Z0-9.]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.8.9'
          echo "Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION"

          mkdir -p ../../artifacts
          cp "$JAR" "../../artifacts/liquidbounce-$LB_VERSION-mc$MINECRAFT_VERSION.jar"

      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liquidbounce-artifact
          path: artifacts/*.jar
